# -*- coding: utf-8 -*-
"""Using NLP to prevent suicide

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15qb0kXnEGh2Ywn2_1NdajruhbXnB8RVm
"""

#Description: This is a sentiment analysis that parses the tweets fetched from Twitter using python

import pandas as pd
import numpy as np

df= pd.read_csv('https://raw.githubusercontent.com/laxmimerit/twitter-suicidal-intention-dataset/master/twitter-suicidal_data.csv')

df.head()

# TFIDF Vector
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report

X = df['tweet']
tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1, 2))
X = tfidf.fit_transform(X)
y = df['intention']

X.shape

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

X_train.shape, X_test.shape

clf = LinearSVC()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

X = 'congratulations, you have done it'
vec = tfidf.transform([X])

clf.predict(vec)

import pickle

pickle.dump(clf, open('model', 'wb'))